### ISSUE TITLE
Tracking Issue: Fix Kritis functionality and enable related integration test

### ISSUE THREAD

**Issue by aaron-prindle** [grafeas/kritis#80]
Currently, Kritis is having issues for the following integration test cases:

- [x] submit no-digest (tag) image
- [x] submit digest image
- [x] submit no-digest (tag) whitelisted image
- [x] submit digest whitelisted image

I believe this stems from two functionality issues:

- [x] Currently Kritis times out when attempting to search CVEs (unsure if auth, query or API change related)
- [x] Whitelisting images is not working as intended (unclear if this is related to above or is a separate issues in the functionality)

**Comment by aaron-prindle** [comment]
it seems that the CVE scanning is working now @HEAD w/ no changes, perhaps something was updated on the container-analysis/GKE side? Marking that fix as done, will update the integration test to test that piece.
